spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.application.name=Merchant-Order
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
server.port=8081
server.error.whitelabel.enabled=true
#  配置中心  與網關轉發
spring:
  application:
    name: merchant-order-service
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
